sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run deploy:dev
  - npm run deploy:prod

after_success:
  - npm run codecov
  - curl --ftp-create-dirs -T dist.tar.gz -u f1101_itenteges:GR6DmL7X6rws ftp://s4.mydevil.net/
