sudo: false
language: node_js
node_js:
  - '6'
addons:
  ssh_known_hosts:
  - s4.mydevil.net
  - 31.186.84.229
install:
  - npm install -g yarn
  - yarn install
script:
  - npm run deploy
after_success:
  - npm run codecov
  - shipit production deploy
