sudo: false
language: node_js
node_js:
  - "6"

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run deploy:dev
  - npm run deploy:prod

after_success:
  - npm run codecov
  - shipit production deploy
